import type { Metadata } from "next";
import { ThemeProvider } from '@mui/material/styles';
import { theme } from "@/app/theme";
import { Box } from "@mui/material";
import { WDXL_Lubrifont_TC } from "next/font/google";

const font = WDXL_Lubrifont_TC({
  subsets: ['cyrillic'],
  weight: ['400'],
  display: 'swap',
  style: ['normal'],
  variable: '--font-wdxl-lubrifont-tc',
  preload: true,
  fallback: ['sans-serif'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <ThemeProvider theme={theme}>
        <Box component="body" sx={{ backgroundColor: 'background.default', fontFamily: font.style.fontFamily }}>
          {children}
        </Box>
      </ThemeProvider>

    </html>
  );
}
